export const mirrorConfig = {
  identity: {
    packageName: "bb-plugin-matt-pocock-skills-for-bb",
    pluginId: "matt-pocock-skills-for-bb",
    cliName: "matt-pocock-skills-for-bb",
    displayName: "Matt Pocock skills for bb",
    shortName: "Matt Pocock skills",
    description: "Matt Pocock's engineering and productivity skills for bb, with experimental skills available by opt-in. Synced daily from mattpocock/skills.",
    icon: "Layers",
    pageId: "matt-pocock-skills",
    pagePath: "matt-pocock-skills",
    rpcPrefix: "matt_pocock_",
    eventChannel: "matt-pocock-skills-state-changed",
  },
  mirror: {
    repo: "erikmackinnon/bb-plugin-matt-pocock-skills-for-bb",
    url: "https://github.com/erikmackinnon/bb-plugin-matt-pocock-skills-for-bb",
    gitUrl: "https://github.com/erikmackinnon/bb-plugin-matt-pocock-skills-for-bb.git",
    issuesUrl: "https://github.com/erikmackinnon/bb-plugin-matt-pocock-skills-for-bb/issues",
    compatUrl: "https://github.com/erikmackinnon/bb-plugin-matt-pocock-skills-for-bb/blob/main/compat/README.md",
  },
  upstream: {
    repo: "mattpocock/skills",
    url: "https://github.com/mattpocock/skills",
    gitUrl: "https://github.com/mattpocock/skills.git",
    ref: "main",
    subdir: ".",
    commitMode: "head",
    metadataPath: ".claude-plugin/plugin.json",
    author: "Matt Pocock",
    license: "MIT",
    attribution: "Matt Pocock skills (MIT), via mattpocock/skills",
  },
  paths: {
    snapshotRoot: "upstream/matt-pocock",
    bundleRoot: "matt-pocock",
    lockFile: "matt-pocock-lock.json",
    catalog: "generated/catalog.json",
    commitMarker: "upstream/UPSTREAM_SHA",
    dateMarker: "upstream/UPSTREAM_COMMITTED_AT",
    runtimeNote: "compat/bb-runtime-note.md",
    skillRoots: ["matt-pocock/skills/engineering", "matt-pocock/skills/productivity", "matt-pocock/skills/in-progress"],
  },
  selection: {
    buckets: ["engineering", "productivity", "in-progress"],
    excludeSkills: ["skills/in-progress/claude-handoff"],
    supportFiles: ["LICENSE"],
    includeCompleteSkillFolders: true,
    metadataExclusions: [".claude-plugin", "README.md", "AGENTS.md", "CLAUDE.md", "skills/*/README.md"],
  },
  defaults: {
    buckets: { engineering: true, productivity: true, "in-progress": false },
    newStableSkills: "bucket-default",
    experimentalRequiresExplicitOn: true,
  },
  skillNames: { aliasPrefix: "matt-pocock-", maxLength: 64, maxCandidates: 256 },
  conflicts: {
    scanIntervalMs: 300_000,
    freshnessMs: 300_000,
    incompletePolicy: "yield-affected-names",
    refreshOn: ["page-open", "explicit-refresh", "plugin-change", "provider-change", "timer"],
    sourceAdapters: ["bb-plugin", "bb-user", "project", "shared-user", "shared-project", "inherited", "provider-user", "provider-project", "native-plugin", "command"],
  },
  dependencies: {
    activationKinds: ["hard", "conditional-hard"],
    reviewedEdges: [
      { from: "grill-with-docs", to: ["grilling", "domain-modeling"], kind: "hard", path: "skills/engineering/grill-with-docs/SKILL.md", lines: [7] },
      { from: "grill-me", to: ["grilling"], kind: "hard", path: "skills/productivity/grill-me/SKILL.md", lines: [7] },
      { from: "implement", to: ["tdd"], kind: "conditional-hard", path: "skills/engineering/implement/SKILL.md", lines: [11] },
      { from: "implement", to: ["code-review"], kind: "hard", path: "skills/engineering/implement/SKILL.md", lines: [15] },
      { from: "implement-spec", to: ["tdd", "code-review"], kind: "hard", path: "skills/engineering/implement-spec/SKILL.md", lines: [29, 36] },
      { from: "tdd", to: ["codebase-design"], kind: "conditional-hard", path: "skills/engineering/tdd/SKILL.md", lines: [26] },
      { from: "improve-codebase-architecture", to: ["codebase-design"], kind: "hard", path: "skills/engineering/improve-codebase-architecture/SKILL.md", lines: [13, 71] },
      { from: "improve-codebase-architecture", to: ["grilling", "domain-modeling"], kind: "conditional-hard", path: "skills/engineering/improve-codebase-architecture/SKILL.md", lines: [64, 66] },
      { from: "triage", to: ["grilling", "domain-modeling"], kind: "conditional-hard", path: "skills/engineering/triage/SKILL.md", lines: [76] },
      { from: "wayfinder", to: ["research"], kind: "conditional-hard", path: "skills/engineering/wayfinder/SKILL.md", lines: [77, 115] },
      { from: "wayfinder", to: ["prototype"], kind: "conditional-hard", path: "skills/engineering/wayfinder/SKILL.md", lines: [78] },
      { from: "wayfinder", to: ["grilling", "domain-modeling"], kind: "hard", path: "skills/engineering/wayfinder/SKILL.md", lines: [79, 111, 124] },
      { from: "retro", to: ["writing-for-agents"], kind: "hard", path: "skills/engineering/retro/SKILL.md", lines: [11, 44] },
      { from: "loop-me", to: ["grilling"], kind: "hard", path: "skills/in-progress/loop-me/SKILL.md", lines: [8] },
      { from: "setup-ts-deep-modules", to: ["codebase-design"], kind: "hard", path: "skills/in-progress/setup-ts-deep-modules/SKILL.md", lines: [11] },
    ],
    dynamicSources: ["ticket-notes", "receiving-agent-advice"],
    routerPolicy: "read-before-recommending-without-cascade",
  },
  prerequisites: {
    commands: ["git", "node", "npm", "pnpm", "bun", "gh", "glab", "bash", "curl", "rg", "jq", "depcruise"],
    trackerCommands: { github: "gh", gitlab: "glab", "local-markdown": null },
    capabilities: ["skill-loading", "delegation", "browser", "human-terminal"],
    commandMatchers: {
      git: "\\bgit\\s+(?:status|diff|log|show|fetch|clone|worktree|commit|rev-parse|branch|push|merge|rebase|checkout)\\b",
      node: "\\bnode\\s+(?:--[\\w-]+\\s+)*[\\w./-]+",
      npm: "\\bnpm\\s+(?:run|ci|install|test|exec)\\b|\\bnpx\\s+[\\w@]",
      pnpm: "\\bpnpm\\s+(?:run|install|test|exec)\\b",
      bun: "\\bbun(?:x)?\\s+(?:run|install|test|add|scripts/|[\\w./-]+\\.ts)",
      gh: "\\bgh\\s+(?:api|auth|pr|issue|repo|run|workflow|release)\\b",
      glab: "\\bglab\\s+(?:api|auth|mr|issue|repo|release)\\b",
      bash: "^#!.*\\bbash\\b|\\bbash\\s+[\\w./-]+\\.sh",
      curl: "\\bcurl\\s+(?:-|https?://)",
      rg: "\\brg\\s+(?:-[\\w]+|[\"'])",
      jq: "\\bjq\\s+(?:-[\\w]+|[\"'])",
      depcruise: "\\b(?:depcruise|dependency-cruiser)\\b",
    },
  },
  startHere: { steps: ["setup-matt-pocock-skills", "ask-matt"] },
  release: {
    syncCron: "17 9 * * *",
    updateCron: "0 */6 * * *",
    concurrencyGroup: "matt-pocock-upstream-sync",
    dataDir: "/tmp/matt-pocock-bb",
    reviewBranch: "sync/upstream",
    reviewLabel: "needs-review",
    commitPrefix: "chore(sync): matt-pocock",
    summaryTrailer: "Matt-Pocock-Sync-Summary: ",
    automaticPublication: true,
    helperPolicy: {
      codeExtensions: [".sh", ".bash", ".zsh", ".fish", ".ksh", ".csh", ".tcsh", ".ps1", ".psm1", ".psd1", ".bat", ".cmd", ".js", ".jsx", ".mjs", ".cjs", ".ts", ".tsx", ".mts", ".cts", ".py", ".pyw", ".rb", ".pl", ".pm", ".php", ".lua", ".r", ".go", ".rs", ".c", ".h", ".cc", ".cpp", ".cxx", ".hpp", ".cs", ".fs", ".fsx", ".java", ".kt", ".kts", ".scala", ".swift", ".m", ".mm", ".dart", ".ex", ".exs", ".erl", ".hrl", ".clj", ".cljs", ".cljc", ".edn", ".hs", ".lhs", ".ml", ".mli", ".jl", ".groovy", ".gradle", ".awk", ".sed", ".sql", ".graphql", ".gql", ".html", ".htm", ".mdx", ".css", ".scss", ".sass", ".less", ".vue", ".svelte", ".astro", ".wasm", ".exe", ".dll", ".so", ".dylib"],
      templateSuffixes: [".template", ".tmpl", ".tpl", ".in", ".example"],
      extensionlessHelpers: ["Makefile", "makefile", "GNUmakefile", "Dockerfile", "Containerfile", "Justfile", "justfile", "Rakefile", "Gemfile", "Vagrantfile", "Procfile"],
      documentationExtensions: [".md", ".markdown", ".txt", ".rst", ".adoc"],
      metadataExtensions: [".yaml", ".yml", ".json", ".jsonc", ".toml", ".ini", ".cfg", ".conf", ".xml", ".csv", ".tsv", ".lock"],
      supportExtensions: [".png", ".jpg", ".jpeg", ".gif", ".webp", ".ico", ".svg", ".pdf", ".woff", ".woff2", ".ttf", ".otf"],
      supportFiles: ["LICENSE", "LICENCE", "COPYING", "NOTICE", ".gitignore", ".gitattributes", ".editorconfig", ".npmrc", ".nvmrc", ".env"],
      unclassifiedPolicy: "review",
    },
  },
  eval: { provider: "codex", model: "gpt-6.1-sol", reasoning: "high", timeoutSeconds: 900, pollSeconds: 5 },
  marketplace: {
    entryPath: "marketplace/matt-pocock-skills-for-bb.json",
    overviewPath: "overview/matt-pocock-skills-for-bb.md",
    screenshotPaths: ["screenshots/matt-pocock-skills-for-bb/overview.png", "screenshots/matt-pocock-skills-for-bb/project.png", "screenshots/matt-pocock-skills-for-bb/dependencies.png", "screenshots/matt-pocock-skills-for-bb/skills.png"],
    category: "code-and-reviews",
    sourceRange: "^0.1.0",
  },
} as const;
